version: '3.1' 

services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 
      ZOO_STANDALONE_ENABLED: 'true'


  pg-master:
    build: '.' 
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    expose:
    - '5432' 
    volumes:
     - '/var/lib/postgresql/data'
    links: ['zoo1']
    #command: su - postgres -c 'patroni /postgres0.yml' 
    command : /bin/bash
    stdin_open: true 
    tty: true

  pg-slave:
    build: '.' 
    restart: always
    expose:
    - '5432' 
    volumes:
     - '/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: '/var/lib/postgresql/data/pgdata'
      REPLICATE_FROM: 'pg-master'
    links: ['pg-master','zoo1']
    #command: su - postgres -c 'patroni /postgres1.yml' 
    command : /bin/bash
    stdin_open: true 
    tty: true
